#!/usr/bin/env python
# SCsub

Import('env')
module_env = env.Clone()
#module_env.Append(CCFLAGS=['-O2'])
#module_env.Append(CXXFLAGS=['-std=c++11'])
module_env.add_source_files(env.modules_sources, "*.cpp")
